# Generated by Django 2.0.7 on 2018-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestEndPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_longitude', models.CharField(max_length=20)),
                ('pickup_latitude', models.CharField(max_length=20)),
                ('dropoff_longitude', models.CharField(max_length=20)),
                ('dropoff_latitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BestPickUpPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_longitude', models.CharField(max_length=20)),
                ('driver_latitude', models.CharField(max_length=20)),
                ('pickup_longitude', models.CharField(max_length=20)),
                ('pickup_latitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_longitude', models.CharField(max_length=20)),
                ('pickup_latitude', models.CharField(max_length=20)),
                ('dropoff_longitude', models.CharField(max_length=20)),
                ('dropoff_latitude', models.CharField(max_length=20)),
                ('pickup_datetime', models.DateTimeField()),
                ('dropoff_datetime', models.DateTimeField()),
            ],
        ),
    ]
