# Generated by Django 2.0.7 on 2018-07-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_geohashpickupplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGeoHashPickUpPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geohash_value', models.CharField(max_length=10)),
                ('point_num', models.IntegerField()),
            ],
        ),
    ]
