# Generated by Django 2.0.7 on 2018-07-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_newgeohashpickupplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGeoHashPickUpPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_longitude', models.CharField(max_length=20)),
                ('pickup_latitude', models.CharField(max_length=20)),
                ('geohash_value', models.CharField(max_length=10)),
                ('point_num', models.IntegerField()),
            ],
        ),
    ]
